server:
  port: ${PORT:0}

spring:
  application:
    name: ms-cart
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cart
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    root: INFO
#    '[com.codearti]': DEBUG
#  file:
#    name: logs/msCart.log   # crea logs/app.log
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': true
        '[format_sql]': true
#        '[event.merge.entity_copy_observer]': allow
    show-sql: true
    defer-datasource-initialization: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://ms-discovery-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
configuration:
  texto: Configurando entorno defecto se actualizo ....