server:
  port: ${PORT:0}

spring:
  
  application:
    name: ms-product
       
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-product
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true
    
#logging:
#  level:
#    root: INFO
#    '[com.codearti]': DEBUG
#  file:
#    name: logs/msProduct.log   # crea logs/app.log


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://ms-discovery-server:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#springdoc:
#
#  title: "Product Api"
#  description: "Api for product"
#  version: "v1.0.0"
#  contact-name: "Robert Tino"
#  contact-email: "w21tino@gmail.com"
#  contact-url: "https://www.devtino.com"
  
#  api-docs:
#    path: /api-docs
##  packages-to-scan:
##  - com.codearti.application.rest
##  paths-to-match:
##  - /v1
#  swagger-ui:
#    path: /swagger-ui.html
##    operations-sorter: alpha
    
  