server:
  port: ${PORT:0}
  
spring:
  application:    name: ms-product
  
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-product
    username: sa
    password: ''
  
  h2:
    console:      enabled: true
      path: /h2-console
  
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true       
   
    
  